# -*- coding: utf-8 -*-
"""deploy_cat_articles.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12t2wEg57ec6oCzbbFH_D4TcB9gxZHpSX
"""

from tensorflow.keras.preprocessing.text import tokenizer_from_json
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import load_model
import numpy as np
import pickle
import json
import os
import re

#1) Trained model --> loading from h.5
#2) Tokenizer --> loading from json
#3) MMS/OHE --> loading from pickle

# to load trained model
loaded_model = load_model(os.path.join('/content/sample_data/model_cat_sentiment.h5'))

loaded_model.summary()

# to load tokenizer
TOKENIZER_PATH = os.path.join('/content/sample_data/tokenizer_cat_sentiment.json')
with open(TOKENIZER_PATH, 'r') as json_file:
    loaded_tokenizer = json.load(json_file)
    
# to load pickle
OHE_PICKLE_PATH = os.path.join('/content/sample_data/ohe_category.pkl')
with open (OHE_PICKLE_PATH, 'rb') as file:
    loaded_ohe = pickle.load(file)

#%%

tokenizer = tokenizer_from_json(loaded_tokenizer)

input_review = input('Type your review here: ')

input_review = re.sub('^\s*|\s\s*',' ',input_review)
input_review = re.sub('[^a-zA-z]',' ',input_review).split()

input_review_encoded = tokenizer.texts_to_sequences(input_review)

input_review_encoded = pad_sequences(np.array(input_review_encoded).T,maxlen=341,
                                     padding='post',
                                     truncating='post')

outcome = loaded_model.predict(np.expand_dims(input_review_encoded,axis=-1))

print(loaded_ohe.inverse_transform(outcome))